name: Deploy

on:
  push:
    branches:
      - hackathon

jobs:
  deploy:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Publish collector locally
      run: |
        git clone --branch 2.3.0 --depth 1 https://github.com/snowplow/stream-collector.git
        cd stream-collector
        sbt publishLocal

    - name: Run sbt
      run: sbt test

    - name: Stage
      if: success()
      run: |
        sbt docker:stage

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build image
      uses: docker/build-push-action@v2
      with:
        context: target/docker/stage
        file: target/docker/stage/Dockerfile
        platforms: linux/amd64,linux/arm64/v8
        tags: snowplow/snowplow-micro:dev
        push: false
